[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"

[env]
PYTHONIOENCODING = "utf-8"
LANG = "C.UTF-8"
LC_ALL = "C.UTF-8"
ENV = "development"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
POSTGRES_HOST = "${{Postgres.PGHOST}}"
POSTGRES_PORT = "${{Postgres.PGPORT}}"
POSTGRES_USER = "${{Postgres.PGUSER}}"
POSTGRES_PASSWORD = "${{Postgres.PGPASSWORD}}"
POSTGRES_DB = "${{Postgres.PGDATABASE}}"