[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicyType = "ON_FAILURE"

[env]
PYTHONPATH = "."
VERSION = "2.2.2"
DEPLOY_FORCE = "true"
NIXPACKS_PYTHON_VERSION = "3.11.6"