services:
  - type: web
    name: brandflow-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8000
      - key: DATABASE_URL
        value: "sqlite+aiosqlite:///./data/brandflow.db"
      - key: SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production
      - key: CORS_ORIGINS
        value: "https://brandflo.netlify.app,http://localhost:3000"
      - key: PYTHONPATH
        value: "/app"