name: Deploy to Railway

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Railway CLI
      uses: railway-app/railway-action@v1
      with:
        railway-token: ${{ secrets.RAILWAY_TOKEN }}
        command: up --detach

    - name: Wait for deployment
      run: sleep 30

    - name: Verify deployment
      run: |
        echo "✅ Railway deployment triggered via GitHub Actions"
        echo "🚀 FastAPI v2.0.0 should be deploying now"
        echo "📋 Check Railway dashboard for deployment status"